<a href="https://colab.research.google.com/github/jansiddiqui/Learning-MachineLearning/blob/main/Day4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from time import process_time

In [6]:
python_list =[i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0009003930000002214


In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00026879099999987943


In [9]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In numpy list - values are separated by commas (,)
But in numpy array - values are not separated by comma(,)


In [11]:
#1D array
a = np.array([1,2,3,3])
print(a)

[1 2 3 3]


In [12]:
a.shape


(4,)

In [14]:
#2D array
b = np.array([(1,2,3,4),(4,5,6,7)])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [15]:
b.shape

(2, 4)

In [23]:
c = np.array([(1,2,3,3),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 3.]
 [5. 6. 7. 8.]]


In [27]:
x = np.zeros((4,5), dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [28]:
y = np.ones((3,3), dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
z = np.full((5,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [33]:

v = np.eye((2))
print(v)

[[1. 0.]
 [0. 1.]]


In [34]:
#numpy array with random value
b = np.random.random((2,3))
print(b)

[[0.41202506 0.75627864 0.39390251]
 [0.74842998 0.031359   0.21590258]]


In [36]:
#random integer value array within a spcific range
c = np.random.randint(10,100,(3,4))
print(c)

[[44 49 25 89]
 [75 29 50 63]
 [85 81 10 52]]


In [41]:
#array of evenly spaced array --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [44]:
#array of evenly spaced value --> spcify the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [45]:
#convert a list  to anumpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analyzing a numpy array

In [46]:
c = np.random.randint(10, 90, (2,3))
print(c)

[[64 10 72]
 [32 39 40]]


In [47]:
#array dimension
print(c.shape)

(2, 3)


In [48]:
#number of dimension
print(c.ndim)

2


In [49]:
#number of elements in the array
print(c.size)

6


In [50]:
#check the data type of the values in the array
print(c.dtype)

int64


MAthematical Operation on NUmpy


In [52]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)  #concatenate or join two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [55]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[0 7 4]
 [6 0 5]
 [4 2 4]]
[[10 14 13]
 [15 11 13]
 [18 11 19]]


In [56]:
print(a + b)

[[10 21 17]
 [21 11 18]
 [22 13 23]]


In [57]:
print(a*b)

[[ 0 98 52]
 [90  0 65]
 [72 22 76]]


In [58]:
print(a-b)

[[-10  -7  -9]
 [ -9 -11  -8]
 [-14  -9 -15]]


In [59]:
print(a/b)

[[0.         0.5        0.30769231]
 [0.4        0.         0.38461538]
 [0.22222222 0.18181818 0.21052632]]


In [60]:
print(a**b)

[[           0 678223072849     67108864]
 [470184984576            0   1220703125]
 [ 68719476736         2048 274877906944]]


In [61]:
print(np.add(a,b))

[[10 21 17]
 [21 11 18]
 [22 13 23]]


In [62]:
print(np.subtract(a,b))

[[-10  -7  -9]
 [ -9 -11  -8]
 [-14  -9 -15]]


In [63]:
print(np.multiply(a,b))

[[ 0 98 52]
 [90  0 65]
 [72 22 76]]


In [64]:
print(np.divide(a,b))

[[0.         0.5        0.30769231]
 [0.4        0.         0.38461538]
 [0.22222222 0.18181818 0.21052632]]


Array Manipulation


In [65]:
array = np.random.randint(0,10,(2,3))
print(array)

[[0 0 5]
 [8 4 6]]


In [66]:
print(array.shape)

(2, 3)


In [67]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 8]
 [0 4]
 [5 6]]
(3, 2)


In [68]:
trans2 = array.T  #method 2
print(trans2)
print(trans2.shape)

[[0 8]
 [0 4]
 [5 6]]
(3, 2)


In [69]:
#reshaping array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 8 5]
 [8 8 8]]
(2, 3)


In [70]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 8]
 [5 8]
 [8 8]]
(3, 2)
